language: python
python:
  - "3.4"
install:
  - "pip install -r requirements/travis.txt"
script:
  - "pep8 --exclude='apps/volontulo/migrations/*,node_modules,.ropeproject' ."
  - "pylint --load-plugins pylint_django --min-similarity-lines=10 volontulo"
  - "coverage run --source='.' manage.py test --settings=volontulo_org.settings.test_settings -v 3"
  - "cd apps/volontulo && npm install && gulp build && cd ../.."
after_success:
  - "codecov"
