language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
script:
  - "pep8 ."
  - "pylint --load-plugins pylint_django volontulo"
  - "coverage run --source=volontulo setup.py test"
after_success:
  - "codecov"
