volontulo:
  image: codeforpoznan/volontulo
  # build: .
  entrypoint: bash docker-entrypoint.sh
  # entrypoint: tail -f /dev/null
  working_dir: /backend
  ports:
    - 8000:8000
  links:
    - db:db
  volumes:
    - ./backend:/backend
    - /backend/apps/volontulo/node_modules

db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: volontulo
    POSTGRES_USER: volontulo
    POSTGRES_DB: volontulo
